name: lint
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: |
            yarn install --frozen-lockfile
            echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: Solhint
        run: yarn solhint 'packages/contracts/contracts/*.sol'

      - name: Prettier
        run: yarn prettier-check
